apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: propdevelopment
  name: admin-sec
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list", "watch" ]
