apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: propdevelopment
  name: admin
subjects:
  - kind: User
    name: admin
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
